### ISSUE TITLE
Hash mismatch with upstream

### ISSUE THREAD

**Issue by joachifm** [slashbeast/grsecurity-scrape#2]
Hi,

> wget https://raw.githubusercontent.com/slashbeast/grsecurity-scrape/master/test/grsecurity-3.1-4.8.7-201611102210.patch

returns a file with sha256

> 64b91cec839a055d78bf9ce17048c617459fd34838ec6da1da4d960d1a767e54

while the same file downloaded from upstream has

> d00203ad69480242aeddf1eab70ac8396c14624a140d3f7972d212ff37dcead8

What could account for this discrepancy?

**Comment by slashbeast** [comment]
They're different in size. 5.3 MB vs 8.9 MB, so most likely there was a network issue.  I suppose I should finally add some error handling to the script as well as checking with the .sig whatever the downloaded file is all right or not.

**Comment by joachifm** [comment]
That makes sense. I believe this has happened once before but then a new version was released before I got around to opening an issue. Most likely the same thing.

For context, I noticed this during routine maintenance for NixOS, where we generate the hash+version info from upstream but rely on your mirror in our package recipe. 

Thank you!

**Comment by slashbeast** [comment]
I will keep it open until I add the things in the script. I will try to get it done tomorrow.

**Comment by slashbeast** [comment]
Sorry for the delay. I've re-wrote the scrape script to handle scraping like a sir.

- All patches are in per-kernel-version directory. Sorry to break your scripts again. :)
- Script fetches gzip-compressed patch which is much faster and does not seems to 'hang' occasionally like with the plain-text one.
- Only if all the fatches went good the patch is actually commited to repository, so no more broken patches there.

Let me know if you see any other issues there.

**Comment by joachifm** [comment]
Sounds good to me. Thank you!
